### ISSUE TITLE
Interacting with Bot over DM fails

### ISSUE THREAD

**Issue by peake100** [peake100/stalkbroker-py#1]
Sending a command to the bot over DM fails because DM messages do not contain guild information.

Stacktrace:

```
Traceback (most recent call last):

  File "/app/.heroku/python/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)

  File "/app/stalkbroker/bot/_commands_ticker.py", line 276, in ticker
    await fetch_ticker(ctx, date_arg)

  File "/app/stalkbroker/bot/_commands_ticker.py", line 187, in fetch_ticker
    stalk_user = await STALKBROKER.db.fetch_user(discord_user.id, message.guild.id)

AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by peake100** [comment]
Resolved by #2
